from turtle import *
from time import*
from math import *
import turtle


bg = turtle.Screen()
bg.bgcolor("black")

list=turtle.Turtle()
list.speed(2)

list.penup()
list.goto(0,200)
list.color("white")
list.write("12 New chapters",font=("arial",20,"bold"),align="center")
sleep(1)

bg.bgcolor("pink")
list.penup()
list.goto(0,150)
list.color("cyan")
list.write("365 New chances ✨",font=("Time New Roman",30,"italic"),align="center")
sleep(1)

bg.bgcolor("violet")
list.penup()
list.goto(0,80)
list.color("pink")
list.write("WAY TO GO!!!",font=("Apple Chancery",50,"underline"),align="center")
sleep(1)

bg.bgcolor("black")
list.penup()
list.goto(0,-10)
list.color("white")
list.write("I hope all your endeavors in 2023 are successful & ",font=("arial",20,"bold"),align="center")
sleep(1)

bg.bgcolor("red")
list.penup()
list.goto(0,-40)
list.color("white")
list.write("this year turns out to be the best year of your life & your family too❤",font=("arial",20,"bold"),align="center")
sleep(1)

bg.bgcolor("blue")
list.penup()
list.goto(0,-70)
list.color("white")
list.write("Wish you a successful & glorious Happy New year 😊",font=("arial",20,"bold"),align="center")
sleep(1)

bg.bgcolor("black")
list.penup()
list.goto(0, -100)
list.color("white")
list.write("♥️",font=("arial",20,"bold"),align="center")
sleep(1)

list.hideturtle()


bg.bgcolor("black")
sleep(0.4)
bg.bgcolor("blue")
sleep(0.4)
bg.bgcolor("violet")
sleep(0.4)
bg.bgcolor("red")
sleep(0.4)
bg.bgcolor("yellow")
sleep(0.2)
bg.bgcolor("white")
sleep(0.2)
bg.bgcolor("black")
sleep(0.4)
bg.bgcolor("blue")
sleep(0.4)
bg.bgcolor("violet")
sleep(0.4)
bg.bgcolor("red")
sleep(0.4)
bgcolor("black")
sleep(4)
list.reset()

penup()
goto(0,220)

color("brown")
write("Yours loving Hasitha",font=("arial",20,"bold"),align="center")

home()

pendown()
pencolor('black')
pensize(3)
fillcolor('yellow')
begin_fill()
circle(100)
end_fill()
pencolor('black')
pensize(6)
penup()
sety(100)
left(150)
forward(35);right(150-90);pendown()
fillcolor('black')
begin_fill()
circle(10)
end_fill();penup()
home();setpos(0,100)
left(30)
forward(35);pendown()
fillcolor('black')
begin_fill();right(30)
circle(10)
end_fill()
penup();home();setpos(-30*3**0.5,100-30);right(60);pendown()
circle(60,120)

sleep(5)